# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestKotlin

# Rules for building the parser.

ErrM.hs LexKotlin.x PrintKotlin.hs ParKotlin.y TestKotlin.hs : Kotlin.cf
	bnfc --haskell Kotlin.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

TestKotlin : TestKotlin.hs ErrM.hs LexKotlin.hs ParKotlin.hs PrintKotlin.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsKotlin.hs AbsKotlin.hs.bak ComposOp.hs ComposOp.hs.bak DocKotlin.txt DocKotlin.txt.bak ErrM.hs ErrM.hs.bak LayoutKotlin.hs LayoutKotlin.hs.bak LexKotlin.x LexKotlin.x.bak ParKotlin.y ParKotlin.y.bak PrintKotlin.hs PrintKotlin.hs.bak SharedString.hs SharedString.hs.bak SkelKotlin.hs SkelKotlin.hs.bak TestKotlin.hs TestKotlin.hs.bak XMLKotlin.hs XMLKotlin.hs.bak ASTKotlin.agda ASTKotlin.agda.bak ParserKotlin.agda ParserKotlin.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak Kotlin.dtd Kotlin.dtd.bak TestKotlin LexKotlin.hs ParKotlin.hs ParKotlin.info ParDataKotlin.hs Makefile


# EOF
