-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsKotlin where

newtype Ident = Ident String
  deriving (Eq, Ord, Read)

instance Show Ident where
    show(Ident name) = name


data Prog = Program [Inst]
  deriving (Eq, Ord, Show, Read)

data Exp
    = Eassign Exp OpAssign Exp
    | Eternary Exp Exp Exp
    | Eor Exp Exp
    | Eand Exp Exp
    | Eeq Exp Exp
    | Eneq Exp Exp
    | El Exp Exp
    | Eg Exp Exp
    | Ele Exp Exp
    | Ege Exp Exp
    | Eadd Exp Exp
    | Esub Exp Exp
    | Emul Exp Exp
    | Ediv Exp Exp
    | Emod Exp Exp
    | Eneg Exp
    | Elneg Exp
    | Einc Exp
    | Edec Exp
    | EPinc Exp
    | EPdec Exp
    | Eiter Iterable
    | Earray Exp Exp
    | Etupla [Exp]
    | Eint Integer
    | Estring String
    | Etrue
    | Efalse
    | Enull
    | Ecall FunctionExp
    | Eget Ident [DimExp]
    | Elambda [Arg] [Stm]
    | Ennass Exp
    | Evar Ident
  deriving (Eq, Ord, Read)

instance Show Exp where
      show (Eassign e1 op e2) = "(" ++ show e1 ++ show op ++ show e2 ++ ")"
      show (Eternary e1 e2 e3) = "(" ++ show e1 ++ show e2 ++ show e3 ++ ")"
      show (Eor e1 e2) = "(" ++ show e1 ++ "||" ++ show e2 ++ ")"
      show (Eand e1 e2) = "(" ++ show e1 ++ "&&" ++ show e2 ++ ")"
      show (Eeq e1 e2) = "(" ++ show e1 ++ "==" ++ show e2 ++ ")"
      show (Eneq e1 e2) = "(" ++ show e1 ++ "!=" ++ show e2 ++ ")"
      show (El e1 e2) = "(" ++ show e1 ++ "<" ++ show e2 ++ ")"
      show (Eg e1 e2) = "(" ++ show e1 ++ ">" ++ show e2 ++ ")"
      show (Ele e1 e2) = "(" ++ show e1 ++ "<=" ++ show e2 ++ ")"
      show (Ege e1 e2) = "(" ++ show e1 ++ ">=" ++ show e2 ++ ")"
      show (Eadd e1 e2) = "(" ++ show e1 ++ "+" ++ show e2 ++ ")"
      show (Esub e1 e2) = "(" ++ show e1 ++ "-" ++ show e2 ++ ")"
      show (Emul e1 e2) = "(" ++ show e1 ++ "*" ++ show e2 ++ ")"
      show (Ediv e1 e2) = "(" ++ show e1 ++ "/" ++ show e2 ++ ")"
      show (Emod e1 e2) = "(" ++ show e1 ++ "%" ++ show e2 ++ ")"
      show (Eneg e) = "-" ++ show e
      show (Elneg e) = "!" ++ show e
      show (Einc e) = "++" ++ show e
      show (Edec e) = "--" ++ show e
      show (EPinc e) = show e ++ "++"
      show (EPdec e) = show e ++ "--"
      show (Eiter e) = "Iterable (" ++ show e ++ ")"
      show (Earray size stm) = "Array (" ++ show size ++ ", " ++ show stm ++ ")"
      show (Etupla e) = "Tupla (" ++ show e ++ ")"
      show (Eint e) = show e
      show (Estring e) = e
      show (Etrue) = "true"
      show (Efalse) = "false"
      show (Enull) = "null"
      show (Ecall (FunCall id [])) = show id ++ "()"
      show (Ecall (FunCall id args)) = show id ++ "(" ++ (foldr1 (\x y -> x ++ "," ++ y) (map show args)) ++ ")"
      show (Eget id dims) = show id ++ (foldr1 (\x y -> x ++ "," ++ y) (map show dims))
      show (Elambda a stms) = "/lambda" -- TODO
      show (Ennass e) = show e ++"!!"
      show (Evar (Ident name)) = name


data DimExp = Dim Exp
  deriving (Eq, Ord, Read)

instance Show DimExp where
      show (Dim e) = "[" ++ show e ++ ""

data OpAssign
    = OpAssign1
    | OpAssign2
    | OpAssign3
    | OpAssign4
    | OpAssign5
    | OpAssign6
  deriving (Eq, Ord, Read)

instance Show OpAssign where
      show (OpAssign1) = "="
      show (OpAssign2) = "+="
      show (OpAssign3) = "-="
      show (OpAssign4) = "*="
      show (OpAssign5) = "/="
      show (OpAssign6) = "%="

data BaseType
    = Ttupla [Type] | Tbool | Tint | Tstring | Tarray Type
  deriving (Eq, Ord, Read)

instance Show BaseType where
      show (Ttupla []) = "Tupla<>"
      show (Ttupla list) = "Tupla<" ++ (foldr1 (\x y -> x ++ "," ++ y) (map show list)) ++ ">"
      show (Tbool) = "Bool"
      show (Tint) = "Int"
      show (Tstring) = "String"
      show (Tarray t) = "Array<" ++ show t ++ ">"

data RetType = TRunit | TRtype Type
  deriving (Eq, Ord, Read)

instance Show RetType where
      show (TRunit) = "Unit"
      show (TRtype t) = show t

data Type
    = Tnullable BaseType | Tnonnull BaseType | Tfun [Type] RetType | Tnull | Help Integer | HelpRet RetType | Tunit
  deriving (Eq, Ord, Read)

instance Show Type where
      show (Tnullable bt) = show bt ++ "?"
      show (Tnonnull bt) = show bt
      show (Tfun [] rt ) = "() -> " ++ show rt
      show (Tfun list rt ) = "(" ++ (foldr1 (\x y -> x ++ "," ++ y) (map show list)) ++ ") -> " ++ show rt
      show (Tnull) = "null"
      show (Tunit) = "Unit"

data Arg = Args Ident Type
  deriving (Eq, Ord, Show, Read)

data Stm
    = Sdec Dec
    | Sexp Exp
    | Sblock [Stm]
    | Sfor Ident Exp [Stm]
    | Swhile Exp [Stm]
    | Sbreak
    | Scont
    | Sretexp Exp
    | Sret
    | Sif Exp [Stm]
    | Sifelse Exp [Stm] [Stm]
    | Sprint Exp
    | Sprintln Exp
    | Snotnull Exp [Stm]
    | Sassert Exp
  deriving (Eq, Ord, Show, Read)

data Inst = Idec Dec
  deriving (Eq, Ord, Show, Read)

data Dec
    = Dfun FunctionDec
    | Dvar Ident Type Exp
    | Dval Ident Type Exp
    | Dvarnull Ident Type
    | Dvalnull Ident Type
  deriving (Eq, Ord, Show, Read)

data FunctionDec = FunDec Ident [Arg] RetType [Stm]
  deriving (Eq, Ord, Show, Read)

data FunctionExp = FunCall Ident [Exp]
  deriving (Eq, Ord, Show, Read)

data Iterable
    = Itrange Exp Exp
    | Itup Exp Exp
    | Itdown Exp Exp
    | Itupst Exp Exp Exp
    | Itdownst Exp Exp Exp
  deriving (Eq, Ord, Show, Read)

